/***************************************************************************
 * Version    Date            Name                   Description
 * =========================================================================
 * v1.0       08-07-2021      Developer2             Sub Method implemented
 ***************************************************************************/
public with sharing class Calculator {
    public Calculator() {
    }   

    public integer add(integer a, integer b){
        return a+b;  
    }   
    public integer sub(integer a, integer b){
        //return result
        return a-b; 
    } 

}

