/***************************************************************************
 * Version    Date            Name                   Description
 * =========================================================================
 * v1.0       08-07-2021      Developer1             Add Method implemented
 ***************************************************************************/
public with sharing class Calculator {
    public Calculator() {
    }   
    public integer add(integer a, integer b){
        return a+b;  
    }   
}

